# Generated by Django 5.0 on 2023-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_xxereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_vulnerable', models.BooleanField(default=False)),
            ],
        ),
    ]
