# Generated by Django 5.0 on 2023-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_sqlireport'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_vulnerable', models.BooleanField(default=False)),
            ],
        ),
    ]
